language: generic 
sudo: required
services:
  - docker
before_install:
  - docker build -t shahin1290/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true shahin1290/docker-react npm run test -- --coverage